# Check point n°2

## Ali LAMINE

# Question 1

In [33]:
a=[]
for i in range (2000, 3201):
    if (i%7==0) and (i%5!=0):
        a.append(i)

print("the output :")
print(a)
        

the output :
[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [36]:
a=[i for i in range (2000, 3201) if (i%7==0) and (i%5!=0)]
print ("the output :\n", a)

the output :
 [2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


# Question 2

In [53]:
def factorial(n):
    if n==0:
        fact=1
    elif n>0:
        fact=n
        for i in range (1,n):
            fact*=i    
    return fact

In [54]:
factorial(5)

120

In [55]:
factorial(0)

1

In [39]:
def factorial(x):
    if x == 1:
        return 1
    else:
        # recursive call to the function
        return (x * factorial(x-1))

# to take input from the user
num = int(input("Enter a number: "))

# call the factorial function
result = factorial(num)
print("The factorial of", num, "is", result)

Enter a number: 1
The factorial of 1 is 1


In [42]:
import math as m
x=int(input("Enter a number: "))
print("The factorial of", x, "is", m.factorial(x))

Enter a number: 5
The factorial of 5 is 120


# Question 3

In [51]:
while True:
    n=int(input("Please, give an intenger >= to 1: "))
    if n>=1:
        dict={}
        for i in range(1,n+1):
            dict[i]=i*i
        break

print("The output is :\n", dict)

Please, give an intenger >= to 1: 8
The output is :
 {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [52]:
# Take User Input of Number

n = int(input("Enter the value of n: "))

# Create a dictionary of squares

squares = {i : i*i for i in range(1, n+1)}

# Print the dictionary

print(squares)

Enter the value of n: 8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


# Question 4

In [1]:
while True:
    string=input("Give a string : ")
    if string!="":
        break

while True:      
    n=int(input("Give an integer between 0 and "+ str(len(string)-1)+ " : "))
    if n in range (0, len(string)):
        break

a=""
for i in range (0, len(string)):
    if i!=n:
        a= a + string[i]
print("missing_char('",string,"', ",n, ") -> '",a,"'", sep="")
    


Give a string : kitten
Give an integer between 0 and 5 : 4
missing_char('kitten', 4) -> 'kittn'


In [2]:
def missing_char(str, n):
  front = str[:n]   # up to but not including n
  back = str[n+1:]  # n+1 through end of string
  return front + back

print(missing_char(string, n))

kittn


# Question 5

In [61]:
# import module
import numpy as np

# create array
print("Original array elements:")
arr = np.array([[0, 1],[2, 3],[4, 5]])
print(arr)
print(type(arr))

# apply method
lis = arr.tolist()

# display list
print("\nArray to list:")
print(lis)
print(type(lis))


Original array elements:
[[0 1]
 [2 3]
 [4 5]]
<class 'numpy.ndarray'>

Array to list:
[[0, 1], [2, 3], [4, 5]]
<class 'list'>


In [59]:
import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


# Question 6

In [71]:
# import module
import numpy as np

# create array 1
arr1 = np.array([[0, 1, 2]])
print("Original Array1:", arr1)

# create array 2
arr2 = np.array([[2, 1, 0]])
print("Original Array2:", arr2)

# calculate covariance 
covar= np.cov(arr1, arr2)

# display result
print("Covariance matrix of the said arrays: \n", covar)


Original Array1: [[0 1 2]]
Original Array2: [[2 1 0]]
Covariance matrix of the said arrays: 
 [[ 1. -1.]
 [-1.  1.]]


# Question 7

In [32]:
# import module
import math as m

# creation of the calculation function 
def prog(D, C=50, H=30):
    Q=m.sqrt((2*C*D)/H)
    return round(Q)

# creation of a function that asks for an input and gives the output
def quest():
    b=input("Give a coma-seperated input ") # asking for the input
    c=b.split(",") # creation of a list of str
    c=[float(i) for i in c] # tranformation to a list of floats
    a=[]
    for i in c:
        a.append(prog(i)) # calculation of the input
    return ",".join(str(element) for element in a) # creation of the output

print("the output is", quest()) # print the result


Give a coma-seperated input 100,150,180
the output is 18,22,24


In [67]:
import math

c = 50
h = 30

value = []

items = [x for x in input("Input Values ").split(',')]

for d in items:
    value.append(str(int(round(math.sqrt(2*c*float(d)/h)))))


print("The followings output are")

print(','.join(value))

Input Values 100,150,180
The followings output are
18,22,24
